


---
spring:
  profiles: eureka-server
  application:
    name: eureka-server-bank

---
spring:
  profiles: slave1
server:
  port: 7001
eureka:
  instance:
    hostname: slave1
  client:
    service-url:
      defaultZone: http://slave2:7002/eureka/
---
spring:
  profiles: slave2
server:
  port: 7002
eureka:
  instance:
    hostname: slave2
  client:
    service-url:
      defaultZone: http://slave1:7001/eureka/

---
spring:
  profiles: standalone
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
