spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_service?useSSL=false
    username: root
    password: enihsyou

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        globally_quoted_identifiers: true

---
spring:
  profiles: euraka-client
  application:
    name: service-bank-api
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

---
spring:
  profiles: standalone
server:
  port: 7101
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

---
spring:
  profiles: slave1
server:
  port: 7101

---
spring:
  profiles: slave2
server:
  port: 7102

